name: Discord Notification
on:
  push:
    branches:
      - main
      - dev
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        run: |
          MESSAGE="🚀 Nouveau push sur ${{ github.repository }} par ${{ github.actor }}\n"
          MESSAGE="$MESSAGE${{ github.event.head_commit.message }}"
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$MESSAGE\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
